name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copiar archivos al servidor EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "docker-compose.yml, prometheus/, app/, Dockerfile, run.py, requirements.txt"
          target: "~/Nexusautoalojado"

      - name: Ejecutar despliegue en EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
          cd Nexusautoalojado
          docker-compose down --remove-orphans
          docker-compose up -d --build

