name: CI/CD Pipeline - Nexusautoalojado

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Crear artefacto tar.gz
      run: |
        tar -czvf app.tar.gz app run.py requirements.txt docker-compose.yml Dockerfile prometheus

    - name: Subir artefacto a Nexus
      run: |
        curl --retry 3 --retry-delay 10 --connect-timeout 60 --max-time 300 -v \
          -u ${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASSWORD }} \
          --upload-file app.tar.gz \
          http://${{ secrets.NEXUS_HOST }}:8081/repository/${{ secrets.NEXUS_REPO }}/app.tar.gz

    - name: Copiar archivos al servidor EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "/home/ec2-user/Nexusautoalojado"

    - name: Ejecutar docker-compose en EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/Nexusautoalojado
          docker-compose down --remove-orphans
          docker-compose up -d --build
